<?php

// menu hook
function queen_attack_menu() {
    $items['queen_attack_input'] = array(
        'title' => 'Queen Attack Form',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('queen_attack_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['queen_attack_output'] = array(
        'title' => 'Queen Attack Results',
        'page callback' => 'queen_attack_result',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function queen_attack_form() {
    $form['x1'] = array(
        '#type' => 'textfield',
        '#title' => 'x position of queen',
        '#required' => TRUE,
    );
    $form['y1'] = array(
        '#type' => 'textfield',
        '#title' => 'y position of queen',
        '#required' => TRUE,
    );
    $form['x2'] = array(
        '#type' => 'textfield',
        '#title' => 'x position of victim',
        '#required' => TRUE,
    );
    $form['y2'] = array(
        '#type' => 'textfield',
        '#title' => 'y position of victim',
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Here we go!',
    );

    return $form;
}

function queen_attack_form_submit($form, &$form_state) {
    $x1 = $form_state['values']['x1'];
    $y1 = $form_state['values']['y1'];
    $x2 = $form_state['values']['x2'];
    $y2 = $form_state['values']['y2'];

    $pieces_are_diagonal = ( abs( $x1 - $x2 ) === abs( $y1 - $y2 ) );

    if( $x1 === $x2 || $y1 === $y2 || $pieces_are_diagonal) {
        $_SESSION['queen_attack'] = "Your victim is in striking range! You may attack.";
    } else {
        $_SESSION['queen_attack'] = "You cannot attack.";
    }
    $form_state['redirect'] = 'queen_attack_output';
}

function queen_attack_result() {
    return $_SESSION['queen_attack'];
}
